<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="OidcProxy.Net.OpenIdConnect" Version="5.4.1" />
    <PackageVersion Include="Spydersoft.Platform.Hosting" Version="2.3.0" />
  </ItemGroup>

</Project>
