sonar.projectKey=spydersoft-consulting_pitstop-web-ui
sonar.javascript.lcov.reportPaths=./src/web/src/pitstop-ui/output/coverage/lcov.info
sonar.sources=./src/web/src/pitstop-ui/src/
sonar.exclusions=**/src/web/src/pitstop-ui/src/api/**/*,**/src/Spydersoft.PitStop.Frontend/**/*
sonar.test.inclusions=**/src/web/src/pitstop-ui/src/**/*.test.{ts,tsx}
sonar.scanner.scanAll=false
